"""Extract only mesh positions/normals/topology. No textures or images are used.
Run with numpy available and source GLB/OBJ files in /private/tmp/naufal-dot-models.
See public/assets/model-credits.txt for source URLs and licenses.
"""
import base64, json, struct, runpy
from pathlib import Path
import numpy as np
SOURCE = Path('/private/tmp/naufal-dot-models')
DEST = Path(__file__).resolve().parents[1] / 'public/assets/models.js'

def glb(name):
    raw=(SOURCE/(name+'.glb')).read_bytes()
    size=struct.unpack_from('<I',raw,12)[0]
    doc=json.loads(raw[20:20+size]); binary=raw[28+size:]
    def read(i):
        a=doc['accessors'][i]; v=doc['bufferViews'][a['bufferView']]
        dtype={5121:'u1',5123:'<u2',5125:'<u4',5126:'<f4'}[a['componentType']]
        dim={'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4}[a['type']]
        offset=v.get('byteOffset',0)+a.get('byteOffset',0)
        return np.ndarray((a['count'],dim),dtype=dtype,buffer=binary,offset=offset,strides=(v.get('byteStride',np.dtype(dtype).itemsize*dim),np.dtype(dtype).itemsize)).copy()
    p=doc['meshes'][0]['primitives'][0]
    vertices=read(p['attributes']['POSITION']); triangles=read(p['indices']).reshape(-1,3)
    frames=[vertices+read(t['POSITION']) for t in p.get('targets',[])]
    return vertices, triangles, frames

def obj():
    vertices=[];triangles=[];group=''
    for line in (SOURCE/'human.obj').read_text().splitlines():
        if line.startswith('v '): vertices.append([float(v) for v in line.split()[1:4]])
        elif line.startswith('g '): group=line[2:]
        elif line.startswith('f ') and group=='body':
            face=[int(v.split('/')[0])-1 for v in line.split()[1:]]
            for i in range(1,len(face)-1): triangles.append([face[0],face[i],face[i+1]])
    v=np.array(vertices); t=np.array(triangles)
    ids, inverse=np.unique(t,return_inverse=True)
    return v[ids], inverse.reshape(-1,3), []

def normals(v,t):
    # Weld coincident positions for smooth light across UV seams.
    _,ids,inverse=np.unique(np.round(v,5),axis=0,return_index=True,return_inverse=True)
    n=np.zeros((len(ids),3)); a,b,c=v[t[:,0]],v[t[:,1]],v[t[:,2]]
    cross=np.cross(b-a,c-a)
    for i in range(3): np.add.at(n,inverse[t[:,i]],cross)
    n/=np.maximum(1e-12,np.linalg.norm(n,axis=1))[:,None]
    return n[inverse]

def b64(a,dtype): return base64.b64encode(np.asarray(a,dtype=dtype).tobytes()).decode()
nature=runpy.run_path(str(Path(__file__).with_name('nature-models.py')))
models={}
for name in ['head','horse','human','bird','flower','mountains','tree']:
    v,t,frames=nature[name]() if name in ['flower','mountains','tree'] else obj() if name=='human' else glb(name)
    if name=='human':
        # Relax the neutral A-pose into a natural standing pose.
        for sign in [-1,1]:
            weight=np.clip((v[:,0]*sign-1.45)/.85,0,1)*(v[:,1]>0.7)
            angle=-.32*weight
            x=v[:,0]*sign-1.55;y=v[:,1]-5.35
            v[:,0]=np.where(weight>0,sign*(1.55+x*np.cos(angle)-y*np.sin(angle)),v[:,0])
            v[:,1]=np.where(weight>0,5.35+x*np.sin(angle)+y*np.cos(angle),v[:,1])
    print(name,'vertices',len(v),'triangles',len(t),'frames',len(frames),'bounds',v.min(0),v.max(0))
    allv=np.concatenate(frames or [v]); center=(allv.max(0)+allv.min(0))/2
    scale=2/np.max(allv.max(0)-allv.min(0))
    sets=frames or [v]
    positions=[];norms=[]
    for verts in sets:
        positions.append(b64(np.round((verts-center)*scale*30000),'<i2'))
        norms.append(b64(np.round(normals(verts,t)*127),'i1'))
    models[name]={'count':len(v),'indices':b64(t,'<u2'),'positions':positions,'normals':norms}
DEST.write_text('// Geometry only. Attribution: model-credits.txt. Generated by scripts/build-models.py.\nwindow.DOT_MODELS='+json.dumps(models,separators=(',',':'))+';\n')
print('Written',DEST.stat().st_size,'bytes')
